#!/bin/bash

function usage {
    echo "usage:"
    echo "rpi-hamclock <action>"
    echo
    echo "  where <action> is one of"
    echo "   'start [-s]' -> start server and browser if option -s is given"
    echo "   'stop'       -> stop rpi-hamclock"
    echo "   'update      -> download latest software version" 
    echo "   'install'    -> build and install software"
    exit 1
}

function update {
    #echo "-> update"

    sudo apt install curl unzip
    rm -rf ESPHamClock
    curl -O https://www.clearskyinstitute.com/ham/HamClock/ESPHamClock.zip
    unzip ESPHamClock.zip
    exit 0
}

function install {
    #echo "-> install"

    #local RESOLUTION=800x480
    local RESOLUTION=1600x960
    #local RESOLUTION=2400x1440
    #local RESOLUTION=3200x1920

    sudo make g++ # libx11-dev libgpiod-dev
    pushd ESPHamClock
    make hamclock-web-${RESOLUTION}
    sudo make install
    popd
    exit 0
}

function start {
    #echo "-> start ($1)"

    local HAMCLOCKURL=http://localhost:8081/live.html
    local DELAY=1

    # wait the desktop system
    sleep 3

    if [ "$1" = "surf" ] ; then
        
        # launch browser
        echo launch surf $HAMCLOCKURL ...
        surf -F $HAMCLOCKURL & SURFPID=$!
        echo pid=$SURFPID.

        # wait for browser ...
        sleep 10
    fi

    # launch hamclock
    echo hamclock ...
    hamclock &
    echo pid=$!

    # wait for hamclock page
    CURLERROR=1
    until [ "${CURLERROR}" -eq "0" ] ; do
	    echo check hamclock ...
	    sleep $DELAY
	    curl -s $HAMCLOCKURL > /dev/null
	    CURLERROR=$?
    done
    echo "hamclock is up :-)"
    exit 0
}

function stop {
    #echo "-> stop"

    killall surf hamclock
    exit 0
}

function dispatch {

    #echo "-> dispatch #$# ($1, $2)" 

    case "$1" in

    update | install | stop )
        [ "$#" = "1" ] && $1
        usage
    ;;

    start)
        [ "$#" = "2" ] && [ "$2" = "-s" ] && start "surf"
        [ "$#" = "1" ] && start
        usage
    ;;

    *)
        usage
    ;;
    
    esac
}

dispatch $@