#!/bin/bash

sudo apt install make unzip
rm -rf ESPHamClock
curl -O https://www.clearskyinstitute.com/ham/HamClock/ESPHamClock.zip
unzip ESPHamClock.zip
pushd ESPHamClock
make -j 4 hamclock-web-1600x960
sudo make install
popd