#!/bin/bash

# initialize script
function initialize {
    #echo "-> init #$# ($*)"

    # find script location on machine
    local script_path="${BASH_SOURCE}"
    while [ -L "${script_path}" ]; do
        local script_dir="$(cd -P "$(dirname "${script_path}")" >/dev/null 2>&1 && pwd)"
        script_path="$(readlink "${script_path}")"
        [[ ${script_path} != /* ]] && script_path="${script_dir}/${script_path}"
    done
    script_path="$(readlink -f "${script_path}")"
    script_dir="$(cd -P "$(dirname -- "${script_path}")" >/dev/null 2>&1 && pwd)"

    # set HAMCLOCK_HOME as working directory
    HAMCLOCK_HOME=$script_dir
    cd $HAMCLOCK_HOME

    # source default configuration config file if available
    [ -r "rpi-hamclock.conf.template" ] && . rpi-hamclock.conf.template

    # source a config file if available
    [ -r "rpi-hamclock.conf" ] && . rpi-hamclock.conf

    # set default values if nothing set
    : ${HAMCLOCK_BUILD_TARGET:=hamclock-web-1600x960}
    : ${HAMCLOCK_AUTOSTART_DELAY:=10}
    : ${HAMCLOCK_BROWSER:=surf}
    : ${HAMCLOCK_RPIHAMCLOCK_GIT_URL:=https://github.com/bubiwahn/rpi-hamclock-web.git}  
    : ${HAMCLOCK_ESPHAMCLOCK_ZIP_URL:=https://www.clearskyinstitute.com/ham/HamClock/ESPHamClock.zip}
    : ${HAMCLOCK_DESKTOP_DIR:=~/Desktop}
    : ${HAMCLOCK_DESKTOP_FILE:=hamclock.desktop}
    : ${HAMCLOCK_AUTOSTART_DIR:=~/.config/autostart}
}

# show configuration config
function config {
    #echo "-> config #$# ($*)"
    echo "rpi-hamclock configuration ..."

    cat << EOM
HAMCLOCK_HOME:                  '${HAMCLOCK_HOME}'
HAMCLOCK_AUTOSTART_DELAY:       '${HAMCLOCK_AUTOSTART_DELAY}'
HAMCLOCK_BROWSER:               '${HAMCLOCK_BROWSER}'
HAMCLOCK_BUILD_TARGET:          '${HAMCLOCK_BUILD_TARGET}'
HAMCLOCK_RPIHAMCLOCK_GIT_URL:   '${HAMCLOCK_RPIHAMCLOCK_GIT_URL}'
HAMCLOCK_ESPHAMCLOCK_ZIP_URL:   '${HAMCLOCK_ESPHAMCLOCK_ZIP_URL}'
HAMCLOCK_DESKTOP_DIR:           '${HAMCLOCK_DESKTOP_DIR}'
HAMCLOCK_DESKTOP_FILE:          '${HAMCLOCK_DESKTOP_FILE}'
HAMCLOCK_AUTOSTART_DIR:         '${HAMCLOCK_AUTOSTART_DIR}'
EOM
    echo "done."
    exit 0
}

# display command line help and exit with code 1
function help {

    cat << EOM 
ESPHamClock on Raspberry Pi install and admin tool.

usage:
rpi-hamclock <TASK>

<TASK> is one of:
    update [-p]         -> update latest software release
                            -p = git pull latest version of rpi-hamclock  
    install [-a]        -> install icon on desktop, where
                            -a = turn on autorun (default=off)
    start [-s [delay]]  -> start service, where
                            -s = show HamClock on local desktop
                            delay = optional delay for autostart after boot
    stop                -> stop service
    config              -> show configuration
EOM
    exit 1
}


# update software
function update {
    #echo "-> update #$# ($*)"
    echo "update with options "$*" ..."

    # if "-p" then git pull rpi-hamclock
    if [ "$1" = "-p" ] ; then
        echo "git pull... "

        git pull

        echo "done."
        exit 0
    fi

    # download hamclock software
    sudo apt install curl unzip g++ ${HAMCLOCK_BROWSER}
    local rc="$?"
    [ "${rc}" != "0" ] && {
        echo "sudo apt install failed. ${HAMCLOCK_BROWSER} might not be available."
        exit "$rc"
    }
    rm -rf ESPHamClock
    curl -O ${HAMCLOCK_ESPHAMCLOCK_ZIP_URL}
    local rc="$?"
    [ "${rc}" != "0" ] && {
        echo "ESPHamClock download failed. ${HAMCLOCK_ESPHAMCLOCK_ZIP_URL} might not be available."
    }
    unzip ESPHamClock.zip

    # build and install software
    pushd ESPHamClock
    make -j 4 ${HAMCLOCK_BUILD_TARGET}
    sudo make install
    popd

    echo "done."
    exit 0
}

# install on desktop
function install {
    # echo "-> install #$# ($*)"
    echo "install hamclock with options "$*" ..."

    # create desktop launcher if requested
    local desktop_dir=$HAMCLOCK_DESKTOP_DIR
    local desktop_path=$desktop_dir/$HAMCLOCK_DESKTOP_FILE

    mkdir -p $desktop_dir
    cat << EOF > $desktop_path
[Desktop Entry]
Name=HamClock
Exec=$HAMCLOCK_HOME/rpi-hamclock start -s ${HAMCLOCK_AUTOSTART_DELAY}
Icon=$HAMCLOCK_HOME/ESPHamClock/hamclock.png
Terminal=false
Type=Application
EOF
    chmod u+x $desktop_path

    # toggle autostart on/off if requested
    local autostart_dir=${HAMCLOCK_AUTOSTART_DIR}
    local autostart_link=${autostart_dir}/${HAMCLOCK_DESKTOP_FILE}
    if [ "$1" = "-a" ] ; then
        mkdir -p ${autostart_dir}
        ln -f -s --target-directory=${autostart_dir} ${desktop_path}
        echo "autostart on"
    else
        [ -f  "${autostart_link}" ] && rm -f "${autostart_link}"   
        echo "autostart off"
    fi

    echo "done."
    exit 0
}

# start service
function start {
    #echo "-> start #$# ($*)"
    echo "start with options "$*" ..."

    local hamclock_url=http://localhost:8081/live.html

    if [ "$1" = "-s" ] ; then
        
        # launch browser
        echo "launch browser ${HAMCLOCK_BROWSER} ..."
        if [ "${HAMCLOCK_BROWSER}" = "surf" ] ; then
            surf -F ${hamclock_url} & local surf_pid=$!
            sleep 3
       elif [ "${HAMCLOCK_BROWSER}" = "midori" ] ; then
            midori -e fullscreen ${hamclock_url} &
        else
            echo "browser '${HAMCLOCK_BROWSER}' is not supported!"
            exit 1
        fi
    fi

    # wait for desktop if auto started
    [ -n "$2" ] && {
        echo "wait $2 secs for desktop ..."
        sleep "$2"
    }

    # launch hamclock
    echo "launch hamclock ..."
    hamclock &
    echo "hamclock_pid=$!"

    # wait for hamclock page
    local delay=1
    curl_error=1
    until [ "${curl_error}" -eq "0" ] ; do
	    echo "check hamclock ..."
	    sleep $delay
	    curl -s $hamclock_url > /dev/null
	    curl_error=$?
    done
    echo "hamclock is up :-)"
    
    # reload page if browser is running
    if [ "${HAMCLOCK_BROWSER}" = "surf" ] ; then
        [ -n "${surf_pid}" ] && kill -HUP "${surf_pid}"
    elif [ "${HAMCLOCK_BROWSER}" = "midori" ] ; then
        midori -e tab-reload
    fi

    echo "done."
    exit 0
}

# stop service
function stop {
    #echo "-> stop #$# ($*)"
    echo "stop ..."

    killall ${HAMCLOCK_BROWSER} hamclock
 
    echo "done."
    exit 0
}

function dispatch {
    #echo "-> dispatch #$# ($*)"

    case "$1" in

    stop | config )
        [ "$#" = "1" ] && $1
        help
    ;;

    update )
        [ "$#" = "2" ] && [ "$2" = "-p" ] && $1 "$2"
        [ "$#" = "1" ] && $1
        help
    ;;

    start )
        [ "$#" = "3" ] && [ "$2" = "-s" ] && $1 "$2" "$3"
        [ "$#" = "2" ] && [ "$2" = "-s" ] && $1 "$2"
        [ "$#" = "1" ] && $1
        help
    ;;

    install )
        [ "$#" = "2" ] && [ "$2" = "-a" ] && $1 "$2"
        [ "$#" = "1" ] && $1
        help
    ;;

    *)
        help
    ;;
    
    esac
}

initialize
dispatch "$@"